### PR TITLE
Plugin Additions

### PR DESCRIPTION
**Pull request by btalberg**
Adds a `Settings > Prosperworks` config page. Accepts an email and API for linking a Prosperworks account to the Prosperworks SDK that was integrated.

Reorg'd some files. Moved JS assets into `Assets > JS`, moved unique functionality to `include/wildflower-<<FUNCTIONALITY>>.php`

Added composer config for plugin and some instructions for setting up dev.

### CODE REVIEW

**Comment by themightymo** [comment]
@btalberg  I am ill-equipped to review the code in this pull request, as I have very little experience with Composer and similar workflow tools.

We are currently working on a code update for the shortcodes within the Wildflower Utilities plugin, specifically in the wildflower-utilities.php file.  Is there anything we need to change on our end from a workflow perspective when we commit these changes?

**Comment by btalberg** [comment]
@themightymo  -  The existing functionality/shortcodes hasn't changed. That code was all moved to `include/wildflower-sites.php`. I added a *require_once* command to load that file from the existing  `wildflower-utilities.php`.

No worries if you haven't worked with composer. The files that composer would fetch are part of the git project, so you would need to use it if you were updating the dependencies. If you could mostly just verify that the plugin still loads/works on your local that should be enough.

**Comment by themightymo** [comment]
@btalberg I did a git push of this _new-plugin-features_ branch to the staging site, and all the shortcode stuff I worked on works fine there.  I also did a spot check on some other features in the "wildflower-sites.php" plugin, and it all checked out.

**Comment by btalberg** [comment]
Thanks for testing out the plugin updates @themightymo . I'll merge this in today.

**Comment by themightymo** [comment]
@btalberg I have some updates to merge into the plugin, but I think it'll be best to wait until this pull request is merged.  When do you expect it will be merged?

**Comment by btalberg** [comment]
@themightymo - changes merged

**Pull request merged**
