### PR TITLE
Add a new shortcode to syndicate any page at any subsite

### PR DESCRIPTION
**Pull request by ramm8313**
Syndicate Any page using the new shortcode, this is the usage

[syndicate post_id=181 blog_id=12]

- blog_id = Is the blog from where the syndication it's going to come and the default value is 1

- post_id = Is the post that you want to syndicate and the default value is 5

### CODE REVIEW

**Comment by themightymo** [comment]
@ramm8313 Since the shortcode only pulls page post types, please change "post_id" to "page_id".

**Comment by ramm8313** [comment]
@themightymo All done but please remember that we need to change ALL the syndicated pages old shortcodes to the new shortcode because we remove the code that creates the old shortcodes

Usage:
[syndicate page_id=5 blog_id=1]

**Comment by themightymo** [comment]
@ramm8313 That makes sense.

I tested out the new shortcodes at http://wildflowerschools-org.wfschools.staging.wpengine.com/our-principles/ and http://wildflowerschools-org.wfschools.staging.wpengine.com/our-network/, and they work great!  Nice work!

@btalberg Will you give this pull request a quick review to confirm that we are integrating with the new plugin structure correctly?

**Comment by themightymo** [comment]
@ramm8313 
The following sub-sites' "Our Network" sorts **don't** work:

- http://violet-wildflowerschools-net.wfschools.staging.wpengine.com/our-network/
- http://alyssum-wildflowerschools-net.wfschools.staging.wpengine.com/our-network/
- http://mnwildflowermontessori-org.wfschools.staging.wpengine.com/our-network/
- http://sweetpea-wildflowerschools-net.wfschools.staging.wpengine.com/our-network/

These ones **DO** work:

- http://zinniamontessori-org.wfschools.staging.wpengine.com/our-network/#
- http://snapdragon-wildflowerschools-net.wfschools.staging.wpengine.com/our-network/#
- http://wildflowerschools-org.wfschools.staging.wpengine.com/our-network/

**Comment by ramm8313** [comment]
@themightymo 
The problem was that in the pages that weren't working the JS code was on the scrip section of each page and it was entering into conflict with the js code that has been syndicated, so I just deleted the code from those pages and now it's working.

Check the attached screenshot to see where was the code

**Comment by themightymo** [comment]
@ramm8313 Good find!  Thank you!  Works now!

**Pull request merged**
